<?php

namespace Database\Seeders;

use App\Models\HealthcareFacility;
use Illuminate\Database\Seeder;

class FacilityDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $facilities = [
            [
                'name' => 'Philippine Heart Center',
                'code' => 'PHC-001',
                'type' => 'Specialty Center',
                'level' => 'tertiary',
                'address' => 'East Avenue, Diliman',
                'city' => 'Quezon City',
                'province' => 'Metro Manila',
                'region' => 'National Capital Region',
                'phone' => '+63-2-8925-2401',
                'email' => 'info@phc.gov.ph',
                'website' => 'https://www.phc.gov.ph',
                'latitude' => 14.6417,
                'longitude' => 121.0491,
                'operating_hours' => ['Monday-Sunday' => '24/7'],
                'is_24_7' => true,
                'has_emergency' => true,
                'services' => ['Cardiology', 'Cardiac Surgery', 'ICU', 'Emergency', 'Laboratory'],
                'bed_capacity' => 400,
                'icu_capacity' => 50,
                'current_bed_availability' => 75,
                'is_public' => true,
                'is_doh_accredited' => true,
                'is_philhealth_accredited' => true,
                'accreditations' => ['DOH Level 3', 'PhilHealth', 'ISO 9001'],
                'accepts_referrals' => true,
                'average_response_time_hours' => 4,
                'preferred_referral_types' => ['High Risk CVD', 'Cardiac Emergency', 'Complex Cases'],
                'is_active' => true,
            ],
            [
                'name' => 'Manila Doctors Hospital',
                'code' => 'MDH-002',
                'type' => 'Tertiary Hospital',
                'level' => 'secondary',
                'address' => '667 United Nations Avenue',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'National Capital Region',
                'phone' => '+63-2-8558-0888',
                'email' => 'info@maniladoctors.com.ph',
                'website' => 'https://www.maniladoctors.com.ph',
                'latitude' => 14.5842,
                'longitude' => 120.9822,
                'operating_hours' => ['Monday-Sunday' => '24/7'],
                'is_24_7' => true,
                'has_emergency' => true,
                'services' => ['Cardiology', 'Internal Medicine', 'Emergency', 'Laboratory'],
                'bed_capacity' => 250,
                'icu_capacity' => 30,
                'current_bed_availability' => 45,
                'is_public' => false,
                'is_doh_accredited' => true,
                'is_philhealth_accredited' => true,
                'accreditations' => ['DOH Level 2', 'PhilHealth', 'JCI'],
                'accepts_referrals' => true,
                'average_response_time_hours' => 6,
                'preferred_referral_types' => ['Moderate Risk CVD', 'General Cardiology'],
                'is_active' => true,
            ],
            [
                'name' => 'Makati Medical Center',
                'code' => 'MMC-003',
                'type' => 'Medical Center',
                'level' => 'tertiary',
                'address' => '2 Amorsolo Street',
                'city' => 'Makati',
                'province' => 'Metro Manila',
                'region' => 'National Capital Region',
                'phone' => '+63-2-8888-8999',
                'email' => 'info@makatimed.net.ph',
                'website' => 'https://www.makatimed.net.ph',
                'latitude' => 14.5622,
                'longitude' => 121.0177,
                'operating_hours' => ['Monday-Sunday' => '24/7'],
                'is_24_7' => true,
                'has_emergency' => true,
                'services' => ['Cardiology', 'Cardiac Surgery', 'ICU', 'Emergency', 'Laboratory', 'Rehabilitation'],
                'bed_capacity' => 500,
                'icu_capacity' => 60,
                'current_bed_availability' => 92,
                'is_public' => false,
                'is_doh_accredited' => true,
                'is_philhealth_accredited' => true,
                'accreditations' => ['DOH Level 3', 'PhilHealth', 'JCI', 'ISO 9001'],
                'accepts_referrals' => true,
                'average_response_time_hours' => 3,
                'preferred_referral_types' => ['High Risk CVD', 'Cardiac Emergency', 'Complex Cases', 'VIP Cases'],
                'is_active' => true,
            ],
            [
                'name' => 'St. Lukes Medical Center - Quezon City',
                'code' => 'SLMC-QC-004',
                'type' => 'Medical Center',
                'level' => 'tertiary',
                'address' => '279 E. Rodriguez Sr. Avenue',
                'city' => 'Quezon City',
                'province' => 'Metro Manila',
                'region' => 'National Capital Region',
                'phone' => '+63-2-8723-0101',
                'email' => 'info@stluke.com.ph',
                'website' => 'https://www.stluke.com.ph',
                'latitude' => 14.6216,
                'longitude' => 121.0191,
                'operating_hours' => ['Monday-Sunday' => '24/7'],
                'is_24_7' => true,
                'has_emergency' => true,
                'services' => ['Cardiology', 'Cardiac Surgery', 'ICU', 'Emergency', 'Laboratory', 'Rehabilitation', 'Research'],
                'bed_capacity' => 650,
                'icu_capacity' => 80,
                'current_bed_availability' => 110,
                'is_public' => false,
                'is_doh_accredited' => true,
                'is_philhealth_accredited' => true,
                'accreditations' => ['DOH Level 3', 'PhilHealth', 'JCI', 'ISO 9001', 'Magnet Recognition'],
                'accepts_referrals' => true,
                'average_response_time_hours' => 2,
                'preferred_referral_types' => ['High Risk CVD', 'Cardiac Emergency', 'Complex Cases', 'Research Cases'],
                'is_active' => true,
            ],
            [
                'name' => 'Quezon City General Hospital',
                'code' => 'QCGH-005',
                'type' => 'Regional Hospital',
                'level' => 'secondary',
                'address' => 'Seminary Road, Bahay Toro',
                'city' => 'Quezon City',
                'province' => 'Metro Manila',
                'region' => 'National Capital Region',
                'phone' => '+63-2-8426-1314',
                'email' => 'info@qcgh.gov.ph',
                'website' => 'https://www.qcgh.gov.ph',
                'latitude' => 14.6907,
                'longitude' => 121.0474,
                'operating_hours' => ['Monday-Sunday' => '24/7'],
                'is_24_7' => true,
                'has_emergency' => true,
                'services' => ['Internal Medicine', 'Emergency', 'Laboratory'],
                'bed_capacity' => 300,
                'icu_capacity' => 20,
                'current_bed_availability' => 25,
                'is_public' => true,
                'is_doh_accredited' => true,
                'is_philhealth_accredited' => true,
                'accreditations' => ['DOH Level 2', 'PhilHealth'],
                'accepts_referrals' => true,
                'average_response_time_hours' => 8,
                'preferred_referral_types' => ['Low to Moderate Risk CVD'],
                'is_active' => true,
            ],
        ];

        foreach ($facilities as $facilityData) {
            HealthcareFacility::updateOrCreate(
                ['code' => $facilityData['code']],
                $facilityData
            );
        }

        $this->command->info('Facility data seeded successfully!');
    }
}
